"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#y)8b3dpp3us-zg5r#%a^57_29w5n3r=z&=7f01#_07u%-xywm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'your-domain.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'LibraryProject.accounts',
    'LibraryProject.bookshelf',
]

AUTH_USER_MODEL = 'accounts.CustomUser'
AUTH_USER_MODEL = 'bookshelf.CustomUser'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===================== SECURITY ENHANCEMENTS =====================

# Force HTTPS redirect for all requests
SECURE_SSL_REDIRECT = True  # Redirect all HTTP requests to HTTPS

# HSTS (HTTP Strict Transport Security)
SECURE_HSTS_SECONDS = 31536000           # One year in seconds
SECURE_HSTS_INCLUDE_SUBDOMAINS = True    # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = True               # Allow site to be preloaded by browsers

# Secure cookies
SESSION_COOKIE_SECURE = True             # Only transmit session cookies over HTTPS
CSRF_COOKIE_SECURE = True                # Only transmit CSRF cookies over HTTPS

# Browser-side protections
SECURE_BROWSER_XSS_FILTER = True         # Enable XSS filtering
X_FRAME_OPTIONS = 'DENY'                 # Prevent clickjacking by denying framing
SECURE_CONTENT_TYPE_NOSNIFF = True       # Prevent MIME type sniffing

# Optional: Content Security Policy (CSP)
# Content Security Policy
CSP_DEFAULT_SRC = ("'self'",)               # allow content only from your domain
CSP_SCRIPT_SRC = ("'self'", "https://cdnjs.cloudflare.com")  # allow scripts from self + CDN
CSP_STYLE_SRC = ("'self'", "https://cdnjs.cloudflare.com")   # allow styles from self + CDN
CSP_IMG_SRC = ("'self'", "data:")          # allow images from self and data URIs
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")       # allow fonts from Google Fonts




